### ISSUE TITLE
Devhub license

### ISSUE THREAD

**Issue by calvinle1** [Appirio/Health-Cloud-Sfdx-Template#8]
Hi, 

Do you need to have Health Cloud installed in Production/Devhub with licenses, in order to create Scratch orgs with the     "HealthCloudUser" feature, and then installed the managed package in the Scratch org?

Thanks

**Comment by roarkely** [comment]
No. Health Cloud licenses are **not required** in your DevHub or Production orgs to create Scratch orgs with the HealthCloudUser feature.

**Comment by calvinle1** [comment]
Hi @roarkely 

Thanks for your reply. When I try to run the orgInit script, it fails with:

ERROR running force:org:create:  An unknown server error occurred. Please try again. If you still see this error, contact Salesforce support for assistance. Include the information from "sfdx force:data:record:get -s ScratchOrgInfo -i

Do you know if there any any steps that need to be done in DevHub/Production prior to the creation of scratch orgs working?
--




ERROR running force:org:create:  An unknown server error occurred. Please try again. If you still see this error, contact Salesforce support for assistance. Include the information from "sfdx force:data:record:get -s ScratchOrgInfo -i 2SR
--



ERROR running force:org:create:  An unknown server error occurred. Please try again. If you still see this error, contact Salesforce support for assistance. Include the information from "sfdx force:data:record:get -s ScratchOrgInfo -i 2SR5m0000000C
--



ERROR running force:org:create:  An unknown server error occurred. Please try again. If you still see this error, contact Salesforce support for assistance. Include the information from "sfdx force:data:record:get -s ScratchOrgInfo -i 2SR5m0000000C
--

**Comment by roarkely** [comment]
This error generally represents a lower-level issue with your org. Sometimes these issues are temporary, but I would recommend contacting Salesforce support.

To learn more about the prerequisites for the use of Scratch orgs and enabling DevHub please see the SFDX [documentation](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs.htm).
